### PR TITLE
Update Dependencies and Github Actions

### PR DESCRIPTION
**Pull request by aidan-casey**
This pull request is more work toward right-aligning dependencies. As I am doing this, I am wondering if it might be okay to require PHP 8.1? There were several broken tests in PHP 8.0.

### CODE REVIEW

**Comment by dgafka** [comment]
@aidan-casey thank you for your work :) 

There is a still big amount of users using `PHP 8.0`, so I would like to stick with it:
https://stitcher.io/blog/php-version-stats-july-2022

Test should be all working on PHP 8.0, if they are broken I can help with fixing. :)

**Comment by aidan-casey** [comment]
@dgafka - Sounds good! I will update accordingly.

**Comment by aidan-casey** [comment]
@dgafka - Care to take a look at this when you have the chance?

**Comment by dgafka** [comment]
@aidan-casey I need to take a look on proxy manager from ocramius before merging that. 
I've dropped this package, as it was failing in PHP 8.1. On the quick look I don't see much have changed, so I am wondering how is this possible that the test are passing now. 

If it does support PHP 8.1, then I will be happy to merge that :)

**Comment by aidan-casey** [comment]
@dgafka - `ocramius/proxy-manager` does not support PHP 8.1, hence why it was added and then subsequently removed in this PR. I would recommend we migrate to that package once it does support PHP 8.1.

`friendsofphp/proxy-manager-lts` is a fork of `ocramius/proxy-manager` that does support PHP 8.1. The problem with failing tests was that a version before v1.0.12 was required, v1.0.12 solves a problem with the generation of a `mixed` return type in the package.

Nothing is different here with the ProxyManager than a simple version bump to ensure the patch is installed.

**Comment by dgafka** [comment]
>  I would recommend we migrate to that package once it does support PHP 8.1.

I agree :) 

> The problem with failing tests was that a version before v1.0.12 was required, v1.0.12 solves a problem with the generation of a mixed return type in the package.

Okey clear, thank you. Merging this ;)

**Pull request merged**
