### PR TITLE
Add mapping from path to repository

### PR DESCRIPTION
**Pull request by aidan-casey**
This pull requests adds a CLI mapping tool for converting the package path to it's repository name. If for whatever reason the repository name is _not_ kebab case of the package name, it can be overridden using the `$overrides` array.

For now I have disabled the actual split functionality, but this can be enabled by uncommenting the correct section of the workflow.

Note that the large number of commits was how long it took me to realize `bin` was in the `.gitignore`. 🤦🏼‍♂️ 😉 

**Edit**: This has been updated. It no longer supports the `$overrides` array but relies on a recursive directory iterator that pulls the package name from the `composer.json` file. This came to mind in anticipation of #33.

### CODE REVIEW

**Comment by dgafka** [comment]
I like the automation. 
I will wait with merging this till all tests and read repositories will be set :)

**Comment by aidan-casey** [comment]
@dgafka - Makes sense! Mainly just wanted to have some plan for it so that it didn't need to get manually updated. 🙂

**Comment by dgafka** [comment]
Can you rebase? :)

**Comment by dgafka** [comment]
I will take care from here and set up read only repositories, thanks :)

**Comment by aidan-casey** [comment]
@dgafka - Sorry for disappearing. In the hospital with my wife as we expect our first child. 🙂

**Comment by dgafka** [comment]
@aidan-casey sure, congratulations! :)

**Pull request merged**
