### PR TITLE
Refactor to Monorepo

### PR DESCRIPTION
**Pull request by aidan-casey**
This pull request begins the migration to an Ecotone monorepo.

### CODE REVIEW

**Comment by aidan-casey** [comment]
@dgafka - Do you want to write up package descriptions and keywords for each individual component in this repository?

Also, while I am messing around with Github actions, is there a particular coding style you want this project to adhere to?

**Comment by dgafka** [comment]
> Note that anyone requiring the ecotone/ecotone dependency will just get the entire framework once the monorepo is up. We can add a composer suggestion that they install only the required component.

Hmmm, let's sum the situation it. 

Current situation:

- Main EcotoneFramework/Ecotone repository is entrypoint, which gets all the stars and points users to documentation and other sub sites.
- Main EcotoneFramework/Ecotone repository is hosted under `ecotone/ecotone` package
- `ecotone/ecotone` package is currently used by user to make use Ecotone Lite. 
- If we will make use `EcotoneFramework/Ecotone` repository as mono-repo and it will be still hosted under `ecotone/ecotone`, then all packages will be pulled by end user

---

Solutions?

One of tenets of Ecotone Framework is to make it as simple as possible to start the project with. 
Requiring package and adding missing service if needed, should enough to make anyone start with defaults. 
Making `ecotone/ecotone` pointing dev repository will be B/C as it will require users that used for example only CQRS, set up Dbal Module related service.

`symfony/symfony` package is not advised to be used, I think they keep it for backward compatibility.
Is there any reason to actually have `ecotone/ecotone` pulling everything?

Solutions?

1. Make `EcotoneFramework/Ecotone` our dev repository and do a breaking change, introduce `Ecotone 2.0`. Introduce `ecotone/ecotone` as pull everything.
2. Introducing `EcotoneFramework/Ecotone-dev` as repository, making `EcotoneFramework/Ecotone` readonly for the `messaging` and `lite` modules pointing to `ecotone/ecotone`.

Are there other ways to not do B/C and keep stars? 
What do you think about second solution?

**Comment by aidan-casey** [comment]
@dgafka - I know it would stink for the stars/downloads, but my gut instinct would be to do a hybrid of those two options:

3. Introduce `EcotoneFramework/Framework` repository which holds the monorepo, at the same time cleaning up the source code as discussed in #24 and release `Ecotone 2.0`. Once done, the `Ecotone/Ecotone` repository can kind of phase itself out with time. This becomes a lot of work, but this might be the time to do it. 😅 

It's a tough call and probably one that comes down to your preference, really.

**Comment by dgafka** [comment]
I ask about your opinions as you help me wider my perspective, which helps to choose the right approach :) 

Ok, so the plan is to allow for big change, let's go with `Ecotone 2.0`! 

Let's keep `ecotoneframework/ecotone` and make it Monorepo.  
`ecotone/ecotone` will basically dispear. 
This means Ecotone will lose stars for packagist. I see it as step back to move few forward :) 

We can introduce `ecotone/messaging`, `ecotone/lite`, those will be separate Read Repos. 
That will require adjusting tutorials, documentation and blog posts. 
I like the idea of pulling `ecotone/lite` separately from `ecotone/laravel` and `ecotone/symfony`, as there is one of them needed at the time, never two.

I will branch out `1.x.x` branch before merging monorepo branch, this will continue support for current version. 
Tell me how can I help with pushing monorepo forward, as this is the first step.
After that we can start planning what to do to make Ecotone more contributor friendly and what to do before releasing `2.0.0`.

Let's the fun begin :)

**Comment by aidan-casey** [comment]
@dgafka - Sounds like a plan! Do you think that maybe we should just rename the current `master` branch to `v1` and begin our monorepo work on `master`?

**Comment by dgafka** [comment]
Yea, `v1` branch pushed: https://github.com/ecotoneframework/ecotone/tree/v1 :)

**Comment by aidan-casey** [comment]
@dgafka - Awesome! Do you want to merge this as an initial refactor to get the monorepo started and then we can begin to come up with a list of items and finesse it a bit?

**Comment by dgafka** [comment]
Hey @aidan-casey,
I would like to do [split testing](https://tomasvotruba.com/blog/2020/02/10/how-to-test-monorepo-after-split-before-actual-split/), to confirm all dependencies are set up right. 

However I think with current structure, as the tests are outside of given package, this will not be possible. 
To make it possible, we would need to move back tests catalog to their corresponding packages.

```
src/Ecotone/Messaging and tests/Messaging
would have move to:
src/Ecotone/Messaging/src and src/Ecotone/Messaging/tests
```

Let me know, what are your thoughts about split testing and the structure :)

**Comment by aidan-casey** [comment]
@dgafka - I could go either way on this one. I like the idea in theory, but looking at Laravel and Symfony, I'm also not seeing this as a common problem.

I also like the fact that in the current structure the tests are removed from the subsplit; I think it help distinguish that it is a readonly repository.

On the other hand, doing split testing would definitely ensure dependencies are set right.

**Comment by dgafka** [comment]
@aidan-casey well I think there is one more advantage of tests inside given package, besides split testing.
If somebody would like to limit context of the work (As IDE search and refactor may be working slow in context of all the packages together), he will be able to do that. 

So I would like to go with this structure :) 

```
src/Ecotone/Messaging/src and src/Ecotone/Messaging/tests
```

Can you adjust the PR? :)

**Comment by dgafka** [comment]
Right now we can just be pragmatic about this and go with the current structure to move forward. 
I can always adjust it later, if I will feel the need for split testing. 

I will take a final look tomorrow morning and if everything will be fine I will be merge the PR :)

**Pull request merged**
